name: Check dependabot pull request

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
    check_pull_request:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4.1.1

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: maven

        - name: Install dependencies
          run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

        - name: Run tests and collect coverage
          run: ./mvnw -B test
#      todo publish test results

    approve_dependabot_pull_request:
      runs-on: ubuntu-latest
      needs: [check_pull_request]
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      steps:
        - name: Dependabot metadata
          id: dependabot-metadata
          uses: dependabot/fetch-metadata@v2
        - name: Enable auto-merge for Dependabot PRs
          if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'rails') && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
          run: gh pr merge --auto --merge "$PR_URL"
          env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    build_docker_img:
      needs: [approve_dependabot_pull_request]
      name: Build and push Docker image
      uses: ./.github/workflows/build_docker_img.yaml
      secrets: inherit

