name: Java Ci

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Install dependencies
        run: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: Run tests and collect coverage
        run: ./mvnw -B test

  build_docker_img:
    needs: [ tests ]
    if: github.ref == 'refs/heads/main'
    name: Build and push Docker image
    uses: ./.github/workflows/build_docker_img.yaml
    secrets: inherit

  create_pr:
    runs-on: ubuntu-latest
    needs: [ tests ]
    if: github.ref == 'refs/heads/dev'
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Artem Nefedov"
          git config user.email "74130706+artemnefedov@users.noreply.github.com"
          git checkout -b dev-auto-pr
          git commit --allow-empty -m "Create PR from dev to main"
          git push origin dev-auto-pr
          gh pr create --base main --head dev-auto-pr --title "PR from dev to main" --body "This PR was automatically created."